image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install
  - command: mysql -e "show databases;"
  - command: redis-server

ports:
  - port: 3002
    onOpen: ignore

github:
  prebuilds:
    main: true
    pullRequests: true
    addComment: true

vscode:
  extensions:
    - editorconfig.editorconfig
    - dbaeumer.vscode-eslint
    - orta.vscode-jest
    - esbenp.prettier-vscode
    - steoates.autoimport
    - coenraads.bracket-pair-colorizer-2
