name: Manual Pipeline

on: [workflow_dispatch]

jobs:
  letsencrypt:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          letsencrypt:enable ${{ github.event.repository.name }}
